### ISSUE TITLE
Not seeing custom properties

### ISSUE THREAD

**Issue by softsolutionsau** [matthiasguentert/ApplicationInsightsRequestLogging#11]
Hi there Matthais,

Firstly, thank you so much for putting this package together, its going to be magnificent as soon as I can get it working! :)

I have done exactly as you have described in the README, except I have included `app.UseAppInsightsHttpBodyLogging();` _outside_ of my `if (env.IsDevelopment())`. I am not using any configuration options (default setup only).

When I look at my App Insights, I do not see the ResponseBody/RequestBody custom properties:
Running on Azure:
![image](https://user-images.githubusercontent.com/37369023/148238663-3ec31d46-360b-4002-ba4d-b6cfb142d052.png)
Running on Local:
![image](https://user-images.githubusercontent.com/37369023/148240604-b6c45d4d-3527-44c1-ab8f-b261fe06445d.png)

Any ideas what I might be doing wrong? Your help would be very much appreciated!

Thanks again,
Shai

**Comment by matthiasguentert** [comment]
Dear Shai, thanks for reaching out!

I can see from your screenshot, that you have `POST`ed to `Account/Login` which resulted in a status code of 200. 

By default, only, failure status codes (4xx, 5xx) and POST, PUT, PATCH verbs are getting logged (see [`BodyLoggerOptions.cs`](https://github.com/matthiasguentert/ApplicationInsightsRequestLogging/blob/main/ApplicationInsightsRequestLogging/ApplicationInsightsRequestLogging/Options/BodyLoggerOptions.cs) for details). If you'd also like to log a status code of 200 you'd have to add it to the list of `HttpCodes` while registering the service

```csharp
using Azureblue.ApplicationInsights.RequestLogging;

var builder = WebApplication.CreateBuilder(args);

// ...
builder.Services.AddAppInsightsHttpBodyLogging(o => 
{
    o.HttpCodes.Add(StatusCodes.Status200OK);
});

// ... 
var app = builder.Build(); 

// ... 
app.UseAppInsightsHttpBodyLogging(); 
```

Please let me know if that solved your issue!

**Comment by softsolutionsau** [comment]
Oh wow, I didn't notice that we were only looking failure codes. That's great, but I still have the issue. Below is a failed attempt at the same endpoint. I must be doing something silly, but I just can't seem to find it...sorry to be a pain.

![image](https://user-images.githubusercontent.com/37369023/148278982-663f6996-014b-41f4-bded-23b25fc83fc9.png)

**Comment by matthiasguentert** [comment]
Hm, then I guess the call to `app.UseAppInsightsHttpBodyLogging();` is happening very late in the pipeline and that the request gets short-circuited before it can reach the logger. 

Please put the call to `app.UseAppInsightsHttpBodyLogging();` as early as possible in your list of middleware components. The order they occur matters. You might also want to have a look here: [Middleware order](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0#middleware-order)

**Comment by softsolutionsau** [comment]
Sir, you are a legend, that is exactly what it was. Thank you!
