### ISSUE TITLE
Make options optional

### ISSUE THREAD

**Issue by crhistianramirez** [matthiasguentert/ApplicationInsightsRequestLogging#2]
As a consumer of this library I'd like to simply add `.AddRequestLogging()` or `.AddResponseLogging()` if my needs are simple and I'm ok with the defaults.

On a related note, 100 characters for MaxSize seems a bit small.  Maybe something like 80kb so that it stays under the ["large object" threshold](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap) which could cause garbage collection issues

I'd be happy to make a pull request with this if you agree it is valuable addition.

**Comment by matthiasguentert** [comment]
Excellent feedback, thank you. Will look into it and reach back.

**Comment by matthiasguentert** [comment]
Implemented with PR: https://github.com/matthiasguentert/ApplicationInsightsRequestLogging/pull/5. I'll prepare a release (but first have to create a github action for that... still young this project 🙂). Thanks again!

**Comment by crhistianramirez** [comment]
Thank you @matthiasguentert this looks great
